title:              Arnav Dhariya
email:              your-email@example.com
description:        Researcher | Writer | Programmer
author:             Arnav Dhariya
url: "https://arnavdhariya.github.io"
baseurl: ""

# Social Profiles
github_username:    arnavdhariya
linkedin_username: Arnav Dhariya

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
